# Azure Container App Job Configuration
# LinkedIn Ads ETL Pipeline
# Schedule: Daily at midnight UTC

apiVersion: apps/v1
kind: Job
metadata:
  name: linkedin-ads-etl-job
  namespace: social-ads
  labels:
    app: linkedin-ads-etl
    platform: linkedin
    environment: production
spec:
  # Cron schedule: Daily at 00:00 UTC
  schedule: "0 0 * * *"

  # Job settings
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  template:
    metadata:
      labels:
        app: linkedin-ads-etl
        platform: linkedin
    spec:
      containers:
      - name: linkedin-ads-etl
        image: acrdigitalreportsdc.azurecr.io/linkedin-ads-etl:latest
        imagePullPolicy: Always

        # Environment variables
        env:
        # LinkedIn credentials
        - name: LINKEDIN_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: linkedin-ads-secrets
              key: client-id
        - name: LINKEDIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: linkedin-ads-secrets
              key: client-secret
        - name: LINKEDIN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: linkedin-ads-secrets
              key: access-token

        # Storage configuration
        - name: STORAGE_TYPE
          value: "vertica"

        # Vertica credentials
        - name: VERTICA_HOST
          value: "vertica11.esprinet.com"
        - name: VERTICA_PORT
          value: "5433"
        - name: VERTICA_DATABASE
          value: "Esprinet"
        - name: VERTICA_SCHEMA
          value: "GoogleAnalytics"
        - name: VERTICA_USER
          valueFrom:
            secretKeyRef:
              name: vertica-secrets
              key: username
        - name: VERTICA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vertica-secrets
              key: password

        # Container App specific
        - name: CONTAINER_MODE
          value: "true"

        # Logging
        - name: LOG_LEVEL
          value: "INFO"

        # Token file (mounted from volume)
        - name: TOKEN_FILE
          value: "/app/data/linkedin_tokens.json"

        # Resource limits
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

        # Volume mounts
        volumeMounts:
        - name: token-cache
          mountPath: /app/data
          readOnly: false

      # Volumes
      volumes:
      - name: token-cache
        persistentVolumeClaim:
          claimName: linkedin-ads-token-pvc

      # Restart policy
      restartPolicy: OnFailure

      # Timeout (1 hour)
      activeDeadlineSeconds: 3600

      # Service account
      serviceAccountName: social-ads-sa
